import _ from "lodash";

const USER_CONSTANTS = {
  GET_OBJECTS_PENDING: "GET_OBJECTS_PENDING",
  GET_OBJECTS_SUCCESS: "GET_OBJECTS_SUCCESS",
  GET_OBJECTS_FAILURE: "GET_OBJECTS_FAILURE"
};

export default _.assignIn({}, USER_CONSTANTS);
